os:
  - linux
services:
  - docker
language: java
#node_js:
#  - "6.9.1"
jdk:
  - oraclejdk8
sudo: false
cache:
  directories:
#    - node
#    - node_modules
    - $HOME/.m2
#env:
#  - NODE_VERSION=6.9.1
before_install:
#  - nvm install $NODE_VERSION
#  - npm install -g npm
#  - npm install -g bower gulp-cli
#  - node -v
#  - npm -v
#  - bower -v
#  - gulp -v
  - java -version
  - chmod +x mvnw
#install: npm install
script:
  - ./mvnw clean
  - ./mvnw test
#  - gulp test
  - ./mvnw package -Pdev -DskipTests
notifications:
  webhooks:
    on_success: change  # options: [always|never|change] default: always
    on_failure: always  # options: [always|never|change] default: always
    on_start: false     # default: false
env:
  global:
    - "FTP_USER=yuyuhui"
    - "FTP_PASSWORD=hnyuyuhui"
after_success:
    "curl --ftp-create-dirs -u $FTP_USER:$FTP_PASSWORD -T ./target/journey-to-the-west-0.0.1-SNAPSHOT.war ftp://120.24.239.239/journey-to-the-west-0.0.1-SNAPSHOT.war"
